### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by arunvickram** [sile-typesetter/casile-demos#7]
This is gonna be a silly question, but I've been looking for a way to change the default for the fancy book, but I'm not able to find the option to do so.

**Comment by alerque** [comment]
Try something like this:

```patch
diff --git a/fancy_book.lua b/fancy_book.lua
index 9d61ef7..28f1df0 100644
--- a/fancy_book.lua
+++ b/fancy_book.lua
@@ -6,6 +6,7 @@ package._name = "fancy_book"
 function package:_init()
   base._init(self)
   self:loadPackage("lorem")
+  SILE.settings.set("font.family", "Familyname", true)
 end
 
 function package:registerCommands ()
```

**Comment by alerque** [comment]
You may also need to *call* a font command at least one. You can avoid doing this is your document by adding it to the `:_init()` function too like `SILE.call("font")`.

**Comment by arunvickram** [comment]
These solutions didn't work. I also tried running `SILE.call("font", { family = "Noto Sans Masaram Gondi" })` and it didn't work either.

**Comment by alerque** [comment]
I just tested the code myself and it seems to work. I posted blink but changing Fontname for an actual font name and regenerating the PDF seems to have worked:

![image](https://user-images.githubusercontent.com/173595/218811117-0b307d1f-0478-42a7-8cea-204bc0e06fe0.png)

Top right is the `git diff`, other right is the command I ran to regenerate the PDF, and left is the PDF clearly showing the default body font has changed to the script one I set.

**Comment by alerque** [comment]
If you are using Docker, did you make sure your font of choice was either:

* installed in the Docker Container,
* in your project's `fonts` directory,
* or mount some directory with the font into the container at run time?

**Comment by alerque** [comment]
If you want to reset the *other* fonts there are some command you can redefine. This example was for setting the default base serif font used where no other style commands set something else. If that isn't what you are testing lets at least make sure this works first.

**Comment by arunvickram** [comment]
> If you are using Docker, did you make sure your font of choice was either:
> 
>     * installed in the Docker Container,
> 
>     * in your project's `fonts` directory,
> 
>     * or mount some directory with the font into the container at run time?

That was the problem. Once I created the `fonts` directory that fixed it.
